trendzproject/home/urls.py
from django.conf.urls import url
from . import views
from home.views import HomeView

urlpatterns = [
	url(r'^$', HomeView.as_view(), name='HomeView')
]

trendzproject/trendz/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
	 login,
	 logout,
	 password_reset,
	 password_reset_done,
	 password_reset_confirm,
	 password_reset_complete
	 	)



urlpatterns = [
	url(r'^$', views.home),
	url(r'^login$', login, {'template_name':'first page/login.html'}, name = 'login'),
	url(r'^logout$', logout, {'template_name':'last page/logout.html'}, name = 'logout'),
	url(r'^register/$', views.register, name='register'),
	url(r'^profile/$', views.view_profile, name='view_profile'),
	url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
	url(r'^change-password/$', views.change_password, name='change_password'),

	url(r'^reset-password/$', password_reset,
	{'template_name':'accounts/reset_password.html',
	 'post_reset_redirect':'trendz:password_reset_done',
	 'email_template_name':'accounts/reset_password_email.html'}, name='password_reset'),

	url(r'^reset-password/done/$', password_reset_done, {'template_name':'accounts/password_reset_done.html'}, name='password_reset_done'),

	url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
	password_reset_confirm, {'template_name':'accounts/password_reset_confirm.html', 'post_reset_redirect':'trendz:password_reset_complete'}, name='password_reset_confirm'),

	url(r'^reset-password/complete/$', password_reset_complete, 
		{'template_name':'accounts/reset_password_complete.html'}, 
		name='password_reset_complete'),
	
	url(r'^news/$', views.news, name='news'),

]

trendzproject/trendzproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from trendzproject import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^$', views.login_redirect, name="login_redirect"),
    url(r'^admin/', admin.site.urls),
    url(r'^trendz/', include('trendz.urls', namespace='trendz')),
    url(r'^home/', include('home.urls', namespace='home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trendzproject/home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

trendzproject/trendz/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class UserProfileManager(models.Manager):
	def get_queryset(self):
		return super(UserProfileManager, self).get_queryset().filter(Area="yapala")

class UserProfileManagerOne(models.Manager):
	def get_queryset(self):
		return super(UserProfileManagerOne, self).get_queryset().filter(Area="Garu/Natinga")

class UserProfile(models.Model):
	user = models.OneToOneField(User)
	Bio = models.TextField(max_length=140, default="")
	Number = models.IntegerField(default=0)
	WhatsApp = models.IntegerField(default=0)
	Email = models.CharField(max_length=100, default="teamtrendz@gmail.com")
	Facebook = models.CharField(max_length=100, default="")
	Area = models.CharField(max_length=100, default="Garu/Natinga")
	image = models.ImageField(upload_to='profile_image', blank=True)

	area = UserProfileManager()
	info = UserProfileManagerOne()

	def __str__(self):
		return self.user.username

	


def create_profile(sender, **kwargs):
	if kwargs['created']:
		user_profile = UserProfile.objects.create(username=kwargs['instance'])

post_save.connect(create_profile, sender=User)	

trendzproject/home/forms.py
from django import forms


class HomeForm(forms.Form):
	post = forms.CharField()

trendzproject/trendz/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import (
	UserCreationForm, 
	UserChangeForm, 
	PasswordChangeForm
		)



class RegistrationForm(UserCreationForm):
	Number = forms.IntegerField(required=True)

	class Meta:
		model = User

		fields = (
			'username',
			'password1',
			'password2'
			)

	def save(self, commit=True):
		user = super(RegistrationForm, self).save(commit=False)
		user.username = self.cleaned_data['username']
		user.password1 = self.cleaned_data['password1']
		user.password2 = self.cleaned_data['password2']

		if commit:
			user.save()
		
		return user



class EditProfileForm(UserChangeForm):

	class Meta:
		model = User

		fields = (
			'username',
			'first_name',
			'last_name',
			'email',
			'password'
			)

trendzproject/home/views.py
from django.views.generic import TemplateView
from django.shortcuts import render,redirect
from home.forms import HomeForm



class HomeView(TemplateView):
	template_name = 'home/home.html'

	def get(self, request):
		form = HomeForm()

		return render(request, self.template_name, { 'form':form })

	def post(self, request):
		form = HomeForm(request.POST)
		if form.is_valid():
			text = form.cleaned_data['post']
			form = HomeForm()
			return redirect('home:HomeView')

		args = {'form': form, 'text': text }
		return render(request, self.template_name, args)

#06-05-18 METAMASK ON.
#turtle meat chase web twist small burger correct meadow angry minor crash

trendzproject/trendz/views.py
from django.shortcuts import render, redirect
from trendz.forms import RegistrationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required

from trendz.forms import EditProfileForm


def home(request):
	return render(request, "home/homepage.html") 


def news(request):
	return render(request, "home/news.html") 

def register(request):
	if request.method == 'POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/trendz/')

	else:
		form = RegistrationForm()

		args = {'form':form}
		return render(request, 'first page/register.html', args)


def view_profile(request):
	args = {'user':request.user}
	return render(request, "accounts/profile.html", args)


def edit_profile(request):
	if request.method == 'POST':
		form = EditProfileForm(request.POST, instance=request.user)
		if form.is_valid():
			form.save()

			return redirect("/trendz/profile/")
	else:
		form = EditProfileForm(instance=request.user)

		args = { 'form':form }
		return render(request, 'accounts/edit_profile.html', args)


def change_password(request):
	if request.method == 'POST':
		form = PasswordChangeForm(data=request.POST, user=request.user)

		if form.is_valid():
			form.save()
			update_session_auth_hash(request, form.user)

			return redirect("/trendz/profile/")

	else:
		form = PasswordChangeForm(user=request.user)
		args = {'form': form}

		return render(request, 'accounts/edit_profile.html', args)


#B1tf11nex123

trendzproject/trendzproject/views.py
from django.shortcuts import redirect

def login_redirect(request):
	return redirect("/trendz/login")

trendzproject/home/templates/home/home.html
{% extends 'base.html' %}



{% block head %}
	<title>HOME</title>
{% endblock %}


{% block float %}
{% endblock %}	

		
{% block body %}
	<title>TRENDZ</title>
	<style>
		
		.footer{
			background-color: lightskyblue;
			overflow: hidden;
			position: fixed;
			bottom:0;
			width: 100%;
		}

		.footer a{
			float:left;
			display: block;
			text-align: center;
			color: white;
			text-decoration: none;
			padding: 10px 16px;
        }
        .footer a:active{
        	background-color: dodgerblue;
        }

        .footer a.active{
        	background-color: dodgerblue;
        }
        .menu{
        	width:20px;
        	height: 4px;
        	background-color: black;
        	margin:2px 0;
        }

        .header{
        	/*float: left;
        	display: block;*/
        	background-color: dodgerblue;
        	padding: 10px;
        }


        .slider{
        	border: 1px dodgerblue;
        	position: relative;
        	
        }
        .name{
        	color:white;
        }
	</style>
</head>
<body>

	<div class="header">
		<p class="name">TRENDZ</p>
		<input type="text" name="search" placeholder="search">
    </div>


    <div class="jumbotron">
        <marquee >
    	<p>"If you don't find a way to make money while you sleep,You will work till you die"-Warren Buffet</p>
        </marquee>
    </div> 




	<div class="container">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }} 
            <button>Submit</button>
        </form>
	</div>  

    <p>{{ text }}</p>

    <div class="footer">
    <a href="#" class="active">TRENDING</a>
    <a href="{% url 'trendz:news' %}">NEWS</a>
    <a href="{% url 'trendz:view_profile' %}">ME</a>    
		
{% endblock %}
	

trendzproject/trendz/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block head %}
<title>PASSWORD CHANGE</title>
{% endblock %}

{% block body %}
	<div class="container">

		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button class="btn btn-info" type="submit">Submit</button>
		</form>
	</div>
{% endblock %}

{% block float %}
<p><br></p>
{% endblock %}
	
</body>
</html>

trendzproject/trendz/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block head %}
<title>PROFILE</title>
<h1 style="background-color:lightskyblue; color: white;">Hi, {{ user.first_name }} {{ user.last_name }}</h1>
<p>Edit your profile account here</p>
{% endblock %}

{% block body %}
	<div class="container">
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button class="btn btn-info" type="submit">Submit</button>
		</form>
	</div>
{% endblock %}

{% block float %}
<p><br></p>
{% endblock %}
	
</body>
</html>

trendzproject/trendz/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block head %}
<title>Enter a new Password</title>
{% endblock %}


{% block body %}

	<div class="container">
		<h3>Enter a new Password</h3>
		<p></p>


		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button class="btn btn-info" type="submit">Reset Password</button>
		</form>
	</div>
{% endblock %}

{% block float %}
{% endblock %}
	
</body>
</html>

trendzproject/trendz/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block head %}
<title>Password reset</title>
{% endblock %}


{% block body %}

	<div class="jumbotron">
	<h3>Password reset sent</h3>

	<p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

	<p>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
	</div>
{% endblock %}

{% block float %}
{% endblock %}
	
</body>
</html>

trendzproject/trendz/templates/accounts/profile.html
{% extends 'base.html' %}

{% block head %}
<title>PROFILE</title>
{% endblock %}


{% block body %}
	<p style="background-color:dodgerblue; color: white; text-align:center; ">
		<a href="/trendz/" style="text-decoration: none; color: white;">𐌉 TRENDZ 𐌉</a> 

		<a href="{% url 'trendz:edit_profile' %}" style="text-decoration: none; color: white;"> Edit Profile 𐌉</a> 

		<a href="{% url 'trendz:change_password' %}" style="text-decoration: none; color: white;"> Change Password 𐌉</a>


		<div class="container">
			<!--
			{% if user.is_authenticated != True %}
			<button style="float: right;" class="btn btn-primary" type="submit">Chat</button>
			{% else %}-->
			<h1>Profile</h1>
			<img src="{{ user.userprofile.image.url }}" width='240'>
			<p>{{ user.first_name }} {{ user.last_name }}</p>
			<p>Area: {{ user.userprofile.Area }}</p>
			<p>Email: {{ user.email }}</p>
			<p>Number: {{ user.userprofile.Number }}</p>
			<p>Whatsapp Number: {{ user.userprofile.Whatsapp }}</p>
			<p>Facebook: {{ user.userprofile.Facebook }}</p>			
			<p>About me: {{ user.userprofile.Bio }}</p>
			

		    <!--{% endif %}-->

			<a href="{% url 'trendz:logout' %}"><button class="btn btn-primary" type="submit">LOG OUT</button></a>
		</div>

		
{% endblock %}

{% block float %}
{% endblock %}
	

trendzproject/trendz/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block head %}
<title>Password reset</title>
{% endblock %}


{% block body %}

	<div class="container">
		<h3>Password reset</h3>
		<p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>


		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button class="btn btn-info" type="submit">RESET</button>
		</form>
	</div>
{% endblock %}

{% block float %}
{% endblock %}
	
</body>
</html>

trendzproject/trendz/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block head %}
<title>Password reset</title>
{% endblock %}


{% block body %}

	<div class="jumbotron">
	<h3>Password reset completed</h3>

	<p>You have successfully resetted your password.</p>
	<p>Click <a href="{% url 'trendz:login' %}">LOG IN</a> to login</p>

	</div>
{% endblock %}

{% block float %}
{% endblock %}
	
</body>
</html>

trendzproject/trendz/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
 	
{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'trendz:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}
	
{% blocktrans %}The {{ site_name }} team{% endblocktrans %}	
{% endautoescape %}

trendzproject/trendz/templates/base.html
<html>
	<head>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
		{% block head %}
		<title>BASE</title>
		{% endblock %}
		<style type="text/css">
			.float{
				float:right;
			}
		</style>

	
	</head>
	<body>
<!--
		<nav class="navbar navbar-light bg-primary justify-content-between">
	  		<a class="navbar-brand">Trendz</a>

	  		<form class="form-inline">
	   			 <input class="form-control mr-xs-2" type="search" placeholder="Search" aria-label="Search">
	    		 <button class="btn btn-info my-2 my-xs-0" type="submit">Search</button>
	  		</form>
		</nav>
-->

	


		{% block float %}
		<div class="jumbotron">
			<a href="/trendz/">TRENDZ</a>
			<div class="float" >
			<a href="{% url 'trendz:password_reset' %}" >   RESET PASSWORD  </a>
			<a href="{% url 'trendz:register' %}">REGISTER</a>
			</div>
		</div>
		{% endblock %}

		{% block body %}
		{% endblock %}

		
	</body>
</html>

trendzproject/trendz/templates/first page/login.html
{% extends 'base.html' %}

{% block head %}
<title>LOG IN</title>
{% endblock %}

{% block body %}
	<div class="container">

		<div class="jumbotron">
		<h1>KENKEN</h1>
		</div>

		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button class="btn btn-info" type="submit">LOG IN</button> 
		</form>
		or <a href="{% url 'trendz:register' %}"><button class="btn btn-info" type="submit">REGISTER</button></a>
		<p>	<a href="{% url 'trendz:password_reset' %}" style="text-decoration: none; color: white;">Reset Password</a> </p>	

	</div>
{% endblock %}

{% block float %}
{% endblock %}
	
</body>
</html>

trendzproject/trendz/templates/first page/register.html
{% extends 'base.html' %}

{% block head %}
<title>REGISTER</title>
{% endblock %}

	{% block float %}
		<div class="jumbotron">
			<h1>REGISTER HERE</h1>
		</div>
	{% endblock %}
		

	{% block body %}
		<div class="container">
			<form method="post">
				{% csrf_token %}
				{{ form.as_p }}
				<button class="btn btn-success" type="submit">REGISTER</button>
			</form>
		</div>
	{% endblock %}


</body>
</html>

trendzproject/trendz/templates/home/homepage.html
{% extends 'base.html' %}



{% block head %}
	<title>HOME</title>
{% endblock %}


{% block float %}
{% endblock %}	

		
{% block body %}
	<title>TRENDZ</title>
	<style>
		
		.footer{
			background-color: lightskyblue;
			overflow: hidden;
			position: fixed;
			bottom:0;
			width: 100%;
		}

		.footer a{
			float:left;
			display: block;
			text-align: center;
			color: white;
			text-decoration: none;
			padding: 10px 16px;
        }
        .footer a:active{
        	background-color: dodgerblue;
        }

        .footer a.active{
        	background-color: dodgerblue;
        }
        .menu{
        	width:20px;
        	height: 4px;
        	background-color: black;
        	margin:2px 0;
        }

        .header{
        	/*float: left;
        	display: block;*/
        	background-color: dodgerblue;
        	padding: 10px;
        }


        .slider{
        	border: 1px dodgerblue;
        	position: relative;
        	
        }
        .name{
        	color:white;
        }
	</style>
</head>
<body>

	<div class="header">
		<p class="name">TRENDZ</p>
		<input type="text" name="search" placeholder="search">
    </div>


    <div class="jumbotron">
        <marquee>
    	<p>"If you don't find a way to make money while you sleep,You will work till you die"-Warren Buffet</p>
        </marquee>
    </div> 


	    <div class="container">

	    <p>{{ username }}</p>
	    <img src="#">
	    <p>like</p>
	    <p>comment</p>
	    </div>  

    <div class="footer">
    <a href="#" class="active">TRENDING</a>
    <a href="{% url 'trendz:news' %}">NEWS</a>
    <a href="{% url 'trendz:view_profile' %}">ME</a>    
		
{% endblock %}
	

trendzproject/trendz/templates/home/news.html
{% extends 'base.html' %}

{% block head %}
<title>PROFILE</title>
{% endblock %}

{% block body %}

		<div class="jumbotron">
			<h1>WELCOME TO THE NEWS CHANNEL OF TRENDZ</h1>
			
		</div>
{% endblock %}

{% block float %}
<p><br></p>
{% endblock %}
	
</body>
</html>

trendzproject/trendz/templates/last page/logout.html
{% extends 'base.html' %}

{% block head %}
<title>LOG out</title>
{% endblock %}



{% block body %}
	<div class="container">
		<div class="jumbotron">
		<h1>TOH NYANG LA</h1>
		</div>
		<h1>You have logged out</h1>
	</div>
{% endblock %}
	
</body>
</html>

#JUST1N4 l0ves ME L1KE 1 D0.